---
- name: This removes httpd webserver
  hosts: all
  tasks:
  - name: ensure httpd is stopped
    service:
      name: httpd 
      state: stopped
  - name: remove apache packages 
    yum:
      name: httpd
      state: absent
